# Generated by Django 5.0.14 on 2026-04-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_customers', '0003_alter_customer_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('console', 'Console'), ('other', 'Other')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('peripherals', models.CharField(blank=True, help_text='e.g. Charger, Case, Cable', max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='b_customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
