# Generated by Django 5.0.14 on 2026-04-08 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_customers', '0004_customer_updated_by_alter_customer_created_by_and_more'),
        ('c_devices', '0002_device_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-created_at'], name='c_devices_d_created_73a01d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['type'], name='c_devices_d_type_1f7143_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['brand'], name='c_devices_d_brand_8a1399_idx'),
        ),
    ]
