# Generated by Django 5.0.14 on 2026-04-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_customers', '0002_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
