# Generated by Django 5.0.14 on 2026-04-05 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d_repairs', '0002_alter_repair_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('down_payment', 'Down Payment'), ('partial', 'Partial Payment'), ('full_settlement', 'Full Settlement')], max_length=20)),
                ('mode_of_payment', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('e_wallet', 'E-Wallet')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference for card/bank/e-wallet payments', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='d_repairs.repair')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
